enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = false
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "19.25.39"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" # fallback

[Music]
enabled = false
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[Music-Extended]
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[YouTube-Extended-inotia]
enabled = true
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
version = "19.16.39"
excluded-patches = "'Custom branding name for YouTube' 'Custom branding icon for YouTube'"
included-patches = "'Enable slide to seek'"
cli-source = "inotia00/revanced-cli"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Extended-inotia]
enabled = true
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
version = "19.30.39"
excluded-patches = "'Custom branding name for YouTube' 'Custom branding icon for YouTube'"
included-patches = "'Enable slide to seek'"
cli-source = "inotia00/revanced-cli"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"


[YouTube-Extended-anddea]
enabled = false
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
version = "19.24.45"
excluded-patches = "'Custom branding name for YouTube' 'Custom branding icon for YouTube'"
included-patches = "'Enable slide to seek'"
cli-source = "inotia00/revanced-cli"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"


[Twitter]
enabled = false
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Twitch]
enabled = false
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[TikTok-Asia-with-sim-spoof]
enabled = false
version = "32.5.3"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
excluded-patches = " 'Remember clear display' 'Playback speed' 'Disable login requirement' 'Spoof Sim Country' 'Spoof Wi-Fi Connection' 'Remove screenshot restriction' 'Export all activities' 'SIM spoof' "
patches-version = "v4.4.0"

[TikTok-Global-without-spoof-sim]
enabled = false
version = "32.5.3"
included-patches = " 'Spoof Wi-Fi connection' 'Remove screenshot restriction' 'Export all activities' 'Predictive back gesture' 'Hide mock location' 'Change version code' 'Spoof build info' 'Override certificate pinning' 'Enable Android debugging' 'Override certificate pinning' 'Remove share targets' 'Remove screen capture restriction' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit-Extended]
enabled = false
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Instagram]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"


[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[Duolingo]
enabled = false
patches-version = "v4.14.0-dev.2"
version = "5.117.4"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/"

[Twitch]
[archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
