enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Extended-inotia]
enabled = true
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "inotia ReVanced"
version = "19.45.38"
excluded-patches = "'Custom branding name for YouTube' 'Custom branding icon for YouTube'"
included-patches = "'Enable slide to seek'"
cli-source = "inotia00/revanced-cli"
build-mode = "both"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube
